// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    ModalCitySelect: typeof import('./src/components/ModalCitySelect.vue')['default']
    ModalItemDetails: typeof import('./src/components/ModalItemDetails.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheHeaderCity: typeof import('./src/components/TheHeaderCity.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
    TheSearch: typeof import('./src/components/TheSearch.vue')['default']
  }
}

export { }
